### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de Comisiones de la Legislatura Actual del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/representantes-patito-2#14]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de Listado de Comisiones de la Legislatura Actual en comisiones del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de Comisiones de la Legislatura Actual:
`GET https://www.congresogto.gob.mx/comisiones/comisiones_api.json`

**Comment by ponentesincausa** [comment]
fixed in c3e28436d994bc2bb60df025f602107ba1b3940d
