### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listado de Leyes del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/representantes-patito-2#3]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de listado de leyes del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listado de Leyes: 
`GET http://www.congresogto.gob.mx/leyes.json`

**Comment by rigobertoguzman** [comment]
Hola, voy a trabajar en este tema.
