### ISSUE TITLE
Actualizar el schema.md añadiendo campos de Listdo de Códigos del Congreso GTO

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/representantes-patito-2#4]
#### Descripción

Actualizar el archivo [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) añadiendo los campos que aparecen en el endpoint de listado de códigos del Congreso de Guanajuato.

#### ¿Qué hay que hacer?

En particular, hay que consumir el endpoint correspondiente y parser la respuesta en formato JSON, ver qué campos de la respuesta no se encuentran actualmente en el [schema.md](https://github.com/CodeandoMexico/representantes-patito-2/blob/master/schema.md) y añadirlos.

#### Endpoint

Listdo de Códigos: 
`GET http://www.congresogto.gob.mx/codigos.json`

**Comment by RodolfoFerro** [comment]
Referencia a: https://github.com/CodeandoMexico/representantes-patito-2/pull/17

**Comment by ponentesincausa** [comment]
corregido y cerrado en bdbf79839a7a67f10d0827ed92d8ff67bc5ab175
